print('====DESAFIO 09====')
num = int(input(
    '\033[32mDigite um número no qual você deseja saber a sua tabuada: \033[m'))
print('tabuada do {}:'.format(num))

print('-' * 12)
print(f'\033[31m{num} x 1 = {num * 1}')
print(f'{num} x 2 = {num * 2}')
print(f'{num} x 3 = {num * 3}')
print(f'{num} x 4 = {num * 4}')
print(f'{num} x 5 = {num * 5}')
print(f'{num} x 6 = {num * 6}')
print(f'{num} x 7 = {num * 7}')
print(f'{num} x 8 = {num * 8}')
print(f'{num} x 9 = {num * 9}')
print(f'{num} x 10 = {num * 10} \033[m')
print('-' * 12)
